# Indicates compatibility version with lifecycle
api = "0.10"

# General metadata about the buildpack that is used be the lifecycle
[buildpack]
  id = "com.jurisfutura/poetry"
  version = "0.0.1"

[[targets]]
  os = "linux"
  arch = "amd64"

# The list of stacks that the buildpack itself is compatible with
[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[metadata]
  [[metadata.dependencies]]
    uri = "https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz"
